global:
  scrape_interval: 15s # By default, scrape targets every 15 seconds.
  evaluation_interval: 15s # By default, scrape targets every 15 seconds.
  external_labels:
    project: latency-404

scrape_configs:
  - job_name: "prometheus"
    scrape_interval: 15s
    static_configs:
      - targets: ["localhost:9090"]

  - job_name: "monitoring-service-local"
    scrape_interval: 15s
    static_configs:
      - targets: ["host.docker.internal:9090"]
    metrics_path: /metrics
    relabel_configs:
      - source_labels: [__address__]
        regex: '([^:]+):\d+'
        target_label: host
        replacement: "${1}"

  # - job_name: "monitoring-service-cloud"
  #   scrape_interval: 15s
  #   static_configs:
  #     - targets: ["localhost:9090"]
  #       metrics_path: /metrics
  #   relabel_configs:
  #     - source_labels: [__address__]
  #       regex: '([^:]+):\d+'
  #       target_label: host
  #       replacement: "${1}"
