{
 "title": "Example Service Latency",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   { "name": "host", "query": { "query": "label_values(host)" } }
  ]
 },
 "panels": [
  {
   "title": "HTTP Health Check Success rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "http_health_check_created{host=\"$host\",status=\"success\"}/http_health_check_created{host=\"$host\"} * 100",
     "legendFormat": "success rate"
    }
   ]
  },
  {
   "title": "HTTP Latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 18, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum by(le) (rate(http_response_time_seconds_bucket{host=\"$host\"}[$__rate_interval])))",
     "legendFormat": "P50"
    },
    {
     "expr": "histogram_quantile(0.9, sum by(le) (rate(http_response_time_seconds_bucket{host=\"$host\"}[$__rate_interval])))",
     "legendFormat": "P90"
    },
    {
     "expr": "histogram_quantile(0.95, sum by(le) (rate(http_response_time_seconds_bucket{host=\"$host\"}[$__rate_interval])))",
     "legendFormat": "P95"
    },
    {
     "expr": "histogram_quantile(0.99, sum by(le) (rate(http_response_time_seconds_bucket{host=\"$host\"}[$__rate_interval])))",
     "legendFormat": "P99"
    }
   ]
  },
  {
   "title": "DNS Health Check Success rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "dns_health_check_created{host=\"$host\",status=\"success\"}/dns_health_check_created{host=\"$host\"} * 100",
     "legendFormat": "success rate"
    }
   ]
  },
  {
   "title": "DNS Latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 18, "x": 6, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum by(le) (rate(dns_response_time_seconds_bucket{host=\"$host\"}[$__rate_interval])))",
     "legendFormat": "P50"
    },
    {
     "expr": "histogram_quantile(0.9, sum by(le) (rate(dns_response_time_seconds_bucket{host=\"$host\"}[$__rate_interval])))",
     "legendFormat": "P90"
    },
    {
     "expr": "histogram_quantile(0.95, sum by(le) (rate(dns_response_time_seconds_bucket{host=\"$host\"}[$__rate_interval])))",
     "legendFormat": "P95"
    },
    {
     "expr": "histogram_quantile(0.99, sum by(le) (rate(dns_response_time_seconds_bucket{host=\"$host\"}[$__rate_interval])))",
     "legendFormat": "P99"
    }
   ]
  },
  {
   "title": "TCP Health Check Success rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "tcp_health_check_created{status=\"success\",host=\"$host\"}/tcp_health_check_created{host=\"$host\"} * 100",
     "legendFormat": "success rate"
    }
   ]
  },
  {
   "title": "TCP Latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 18, "x": 6, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum by(le) (rate(tcp_response_time_seconds_bucket{host=\"$host\"}[$__rate_interval])))",
     "legendFormat": "P50"
    },
    {
     "expr": "histogram_quantile(0.9, sum by(le) (rate(tcp_response_time_seconds_bucket{host=\"$host\"}[$__rate_interval])))",
     "legendFormat": "P90"
    },
    {
     "expr": "histogram_quantile(0.95, sum by(le) (rate(tcp_response_time_seconds_bucket{host=\"$host\"}[$__rate_interval])))",
     "legendFormat": "P95"
    },
    {
     "expr": "histogram_quantile(0.99, sum by(le) (rate(tcp_response_time_seconds_bucket{host=\"$host\"}[$__rate_interval])))",
     "legendFormat": "P99"
    }
   ]
  },
  {
   "title": "Ping (ICMP) Health Check Success rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "ping_health_check_created{host=\"$host\",status=\"success\"}/ping_health_check_created{host=\"$host\"} * 100",
     "legendFormat": "success rate"
    }
   ]
  },
  {
   "title": "Ping (ICMP) Latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 18, "x": 6, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum by(le) (rate(ping_response_time_seconds_bucket{host=\"$host\"}[$__rate_interval])))",
     "legendFormat": "P50"
    },
    {
     "expr": "histogram_quantile(0.9, sum by(le) (rate(ping_response_time_seconds_bucket{host=\"$host\"}[$__rate_interval])))",
     "legendFormat": "P90"
    },
    {
     "expr": "histogram_quantile(0.95, sum by(le) (rate(ping_response_time_seconds_bucket{host=\"$host\"}[$__rate_interval])))",
     "legendFormat": "P95"
    },
    {
     "expr": "histogram_quantile(0.99, sum by(le) (rate(ping_response_time_seconds_bucket{host=\"$host\"}[$__rate_interval])))",
     "legendFormat": "P99"
    }
   ]
  }
 ]
}