services:
  monitoring-service:
    container_name: monitoring-service
    init: true
    platform: linux/amd64
    restart: always
    image: ghcr.io/thonglmt/latency-404/monitoring-service:0.0.3
    ports:
      - "9090:9090"
    environment:
      - PORT=9090
      - TARGET_HOST=example.example-corp.internal
      - TARGET_PORT=8000
      - TARGET_PATH=/health
      - CHECK_INTERVAL=15
    networks:
      - example
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9090/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

networks:
  example:
    driver: bridge
